//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockExchange {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StockExResr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StockExResr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockExchange.StockExResr", typeof(StockExResr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GraphData_.
        /// </summary>
        internal static string Graph_Prefix {
            get {
                return ResourceManager.GetString("Graph_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph_Times.
        /// </summary>
        internal static string Graph_Times_Var {
            get {
                return ResourceManager.GetString("Graph_Times_Var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully changed your password..
        /// </summary>
        internal static string ManagePasswordChangeSuccess {
            get {
                return ResourceManager.GetString("ManagePasswordChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully modified your wallet..
        /// </summary>
        internal static string ManageWalletChangeSuccess {
            get {
                return ResourceManager.GetString("ManageWalletChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://webtask.future-processing.com:8068/stocks/.
        /// </summary>
        internal static string Price_Provider_Url {
            get {
                return ResourceManager.GetString("Price_Provider_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6esu31wctl.
        /// </summary>
        internal static string Site_Owned_Id {
            get {
                return ResourceManager.GetString("Site_Owned_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have enough funds in your account..
        /// </summary>
        internal static string StocksNotEnoughBalance {
            get {
                return ResourceManager.GetString("StocksNotEnoughBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We did not have {0} {1} stocks to sell. Amount available: {2}..
        /// </summary>
        internal static string StocksNotEnoughToSellSite {
            get {
                return ResourceManager.GetString("StocksNotEnoughToSellSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have {0} {1} stocks to sell..
        /// </summary>
        internal static string StocksNotEnoughToSellUser {
            get {
                return ResourceManager.GetString("StocksNotEnoughToSellUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfuly bought {0} {1} stocks for {2} PLN..
        /// </summary>
        internal static string StocksPurchaseSuccesful {
            get {
                return ResourceManager.GetString("StocksPurchaseSuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfuly sold {0} {1} stocks for {2} PLN..
        /// </summary>
        internal static string StocksSaleSuccesful {
            get {
                return ResourceManager.GetString("StocksSaleSuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We currently support between 0 and 100000 PLN in account balance..
        /// </summary>
        internal static string ValidationAccBalanceOOR {
            get {
                return ResourceManager.GetString("ValidationAccBalanceOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address cannot be longer than 100 characters..
        /// </summary>
        internal static string ValidationEmailCharLimit {
            get {
                return ResourceManager.GetString("ValidationEmailCharLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be longer than 100 characters..
        /// </summary>
        internal static string ValidationPasswordCharLimit {
            get {
                return ResourceManager.GetString("ValidationPasswordCharLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        internal static string ValidationPasswordMismatch {
            get {
                return ResourceManager.GetString("ValidationPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        internal static string ValidationPasswordMismatchNew {
            get {
                return ResourceManager.GetString("ValidationPasswordMismatchNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We currently support up to 1000 single company stocks per user..
        /// </summary>
        internal static string ValidationStocksLimit {
            get {
                return ResourceManager.GetString("ValidationStocksLimit", resourceCulture);
            }
        }
    }
}
